name: Build iOS Release App

on:
  push:
    branches:
      - master
  workflow_call:

jobs:
  build-release-ios:
    name: Build iOS Release App
    runs-on: macOS
    steps:
      - name: ğŸ— Checkout repository
        uses: actions/checkout@v4

      - name: ğŸ“¦ Install dependencies
        run: nix develop .# --command bash -c "bun install --frozen-lockfile"

      - name: ğŸ› ï¸ Build
        run: nix develop .# --command bash -c "bun client ios:prebuild && bun client build:ios:ci"

      - name: ğŸ“ Prepare build output
        run: |
          mkdir ios-release-build
          mv client/ios/build/Build/Products/Release-iphonesimulator/Noah-Regtest.app ios-release-build/ios-release.app

      - name: ğŸ“¤ Upload iOS app artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-release-app
          path: ios-release-build/
