name: Build iOS Release App

on:
  push:
    branches:
      - master # Build on main for caching purposes, this way every branch will have access to it
  workflow_call:
    outputs:
      build-cache-key:
        description: "The primary key used for caching the build"
        value: ios-release-build-${{ jobs.lookup-cached-build.outputs.fingerprint }}

jobs:
  lookup-cached-build:
    name: Lookup cached release build
    uses: ./.github/workflows/noah-lookup-cached-release-build.yml
    with:
      platform: ios

  build-release-ios:
    name: Build iOS Release App
    needs: lookup-cached-build
    if: needs.lookup-cached-build.outputs.build-exists != 'true'
    runs-on: macOS
    steps:
      - name: ğŸ— Checkout repository
        uses: actions/checkout@v4

      - name: ğŸ“¦ Install dependencies
        run: nix develop .# --command bash -c "bun install --frozen-lockfile"

      - name: ğŸ› ï¸ Build
        run: nix develop .# --command bash -c "bun client ios:prebuild && bun client build:ios:ci"

      - name: ğŸ“ Prepare cache folder
        run: |
          mkdir ios-release-build
          mv client/ios/build/Build/Products/Release-iphonesimulator/Noah-Regtest.app ios-release-build/ios-release.app

      - name: ğŸ“¡ Store built app in cache
        id: ios-release-save
        uses: actions/cache/save@v4
        with:
          path: ios-release-build/
          key: ios-release-build-${{ needs.lookup-cached-build.outputs.fingerprint }}
