name: Build iOS Release Simulator App

on:
  workflow_call:
    outputs:
      artifact_name:
        description: "The name of the uploaded artifact"
        value: ${{ jobs.build-release-ios.outputs.artifact_name }}
      app_filename:
        description: "The filename of the iOS app"
        value: ${{ jobs.build-release-ios.outputs.app_filename }}

jobs:
  build-release-ios:
    name: Build iOS Release App
    runs-on: macOS
    outputs:
      artifact_name: ${{ steps.set_outputs.outputs.artifact_name }}
      app_filename: ${{ steps.set_outputs.outputs.app_filename }}
    steps:
      - name: ğŸ— Checkout repository
        uses: actions/checkout@v4

      - name: ğŸ“¦ Install dependencies
        run: nix develop .# --command bash -c "bun install --frozen-lockfile"

      - name: ğŸ› ï¸ Build
        run: nix develop .# --command bash -c "bun client ios:prebuild && /usr/bin/git diff --exit-code -- client/ios/Podfile.lock && bun client build:ios:ci"

      - name: ğŸ“ Prepare build output
        id: set_outputs
        run: |
          mkdir ios-release-build
          mv client/ios/build/Build/Products/Release-iphonesimulator/Noah-Regtest.app ios-release-build/ios-release.app
          echo "artifact_name=ios-release-app" >> $GITHUB_OUTPUT
          echo "app_filename=ios-release.app" >> $GITHUB_OUTPUT

      - name: ğŸ—œï¸ Compress iOS app
        run: |
          cd ios-release-build
          zip -r -y ios-release.zip ios-release.app
          rm -rf ios-release.app

      - name: ğŸ” Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: ğŸ“¤ Upload iOS app to S3
        run: aws s3 cp ios-release-build/ios-release.zip s3://${{ secrets.AWS_S3_BUCKET }}/ci-artifacts/${{ github.run_id }}/ios-release.zip
