name: Master Server Build and Push

on:
  push:
    branches:
      - master
    paths:
      - "server/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".github/workflows/server-push.yml"

jobs:
  fmt-check:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: âœ¨ Check formatting
        run: nix develop .#server --command bash -c "cargo fmt --check"
  test:
    runs-on: self-hosted
    needs: fmt-check
    steps:
      - uses: actions/checkout@v4
      - name: ğŸ§ª Run tests
        run: nix develop .#server --command bash -c "cargo test"
  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: ğŸ— Checkout code
        uses: actions/checkout@v4

      - name: âš™ï¸ Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: ğŸ‹ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: ğŸ” Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸš€ Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/blixtwallet/noah-server:latest
